[package]
name = "kokiri"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
tempfile = "3.13.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
